### ISSUE TITLE
Add a function for /coins/{id}/contract/{contract_address} coingecko endpoint

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Niraj-Kamdar/defiwrapper#28]
For more details look at #4

**Comment by rihp** [comment]
The Defiwrapper team has assigned a reward of 500 USDC, paid through polygon, to the person(s) who's able to finish this high priority task.

Initially the issue has been assigned to James C.
 - @codeproline
 - Pro-Dev0219#4992
 
We've transferred [10% of the total amount]() to James a retainer fee, per his request, to begin tackling the issue and collaborating.
 
 Welcome to the team @codeproline! :zap:

**Comment by rihp** [comment]
[Txn of $450](https://polygonscan.com/tx/0x62c7070806198009cc00c9bef9215e0f3cefb79b2b24a24ce0af0ede38be968a) to @codeproline for closing the issue 👏 thanks again dude :)
