### ISSUE TITLE
Add a function for /coins/{id}/contract/{contract_address}/market_chart/ coingecko endpoint

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Niraj-Kamdar/defiwrapper#29]
For more details look at #4

**Comment by codeproline** [comment]
Hello. everyone.
@codeproline  will do this issue.

**Comment by Niraj-Kamdar** [comment]
Can you link the PR here

**Comment by Niraj-Kamdar** [comment]
[Txn of $500](https://polygonscan.com/tx/0x4602d767ea5d1b585009685e588d11a137324e1e0c66725e1ad7b35a6d4bdb40) to @codeproline for closing the issue 👏 thanks again dude :)

**Comment by Niraj-Kamdar** [comment]
Here's the PR link: #92
